#!/bin/bash

#each machine needs to have the NFS volume mounted to
#/mnt/dlink_nfs/
#each machine needs to have rsync installed and the script linked in crontab
#exclude file will exclude from all machines unless specified otherwise relative path to the source
source /mnt/dlink_nfs/backup-script/var-dec

if [[ $1 == 'clean' ]]
	then
	echo "clean command passed"
	rsync -va --delete-after --exclude-from=$FOLDER_NFS/backup-script/exclude.lst /home/$USER $FOLDER_NFS/backup-test/$DIRNAME
	exit 1
	else
	rsync -va --exclude-from=$FOLDER_NFS/backup-script/exclude.lst --delete-excluded /home/$USER $FOLDER_NFS/backup-test/$DIRNAME
fi
