#!/bin/bash

#each machine needs to have the NFS volume mounted to
#/mnt/dlink_nfs/
#each machine needs to have rsync installed and the script linked in crontab
#exclude file will exclude from all machines unless specified otherwise relative path to the source
source /mnt/dlink_nfs/backup-script/var-dec

rsync -va --delete-after --delete-excluded --exclude-from=$FOLDER_NFS/backup-script/exclude.lst /home/$USER $FOLDER_NFS/backup-test/$DIRNAME
