#!/bin/bash
#This file syncs the network drives together

source /mnt/dlink_nfs/backup-script/var-dec

if pidof -x "$script_name" -o $$ >/dev/null;then
   echo "An another instance of this script is already running"
   exit 1
fi

DOW=$(date +"%a")

if [ "$DOW" == "Sat" ]; then
#rsync -rtDvmhz --delete-before $FOLDER_NFS/$FOLDER  /mnt/synology2
#echo rsync -avh --delete-before --exclude-from=$FOLDER_NFS/backup-script/exclude.lst $FOLDER_NFS/backup-script/ /mnt/synology2/backup-script
#rsync -rtDvmhz --delete-before --exclude-from=$FOLDER_NFS/backup-script/exclude.lst $FOLDER_NFS/backup-script/ /mnt/synology2/backup-script
rsync -rtDvhmz --exclude '#recycle' $FOLDER_NFS/$FOLDER/ /mnt/synology1
else
#echo rsync -rtDvmhz $FOLDER_NFS/$FOLDER  /mnt/synology2
#echo rsync -rtDvmhz $FOLDER_NFS/backup-script/ /mnt/synology2/backup-script
rsync -rtDvbhmz --exclude '#recycle' $FOLDER_NFS/$FOLDER/ /mnt/synology1/$FOLDER
fi

#tar -cvf /mnt/synology1/old_data.tar /mnt/synology1/backup-test
