#!/bin/bash
#This file syncs the network drives together

source /mnt/dlink_nfs/backup-script/var-dec

if pidof -x "$script_name" -o $$ >/dev/null;then
   echo "An another instance of this script is already running"
   exit 1
fi

DOW=$(date +"%a")

if [ "$DOW" == "Sat" ]; then
echo Saturday.
rsync -avbh --delete-before $FOLDER_NFS/$FOLDER  /mnt/synology2
rsync -avbh --delete-before $FOLDER_NFS/backup-script /mnt/synology2/backup-script
rsync -rtDpovbhz --delete-before $FOLDER_NFS_SYN2/$FOLDER /mnt/synology1
else
rsync -avbh $FOLDER_NFS/$FOLDER  /mnt/synology2
rsync -avbh $FOLDER_NFS/backup-script /mnt/synology2/backup-script
rsync -rtDpovbhz $FOLDER_NFS_SYN2/$FOLDER /mnt/synology1
echo no clean
fi
