#!/bin/bash
#set -x
script_name=$(basename -- "$0")
s3_cmd="sync -rHv --no-check-md5 --delete-removed --skip-existing --acl-private --continue-put --storage-class=STANDARD_IA  --exclude-from=/mnt/dlink_nfs/backup-script/s3_exclude"
s3_bucket=s3://linux-bck/backup/

if pidof -x "$script_name" -o $$ >/dev/null;then
   echo "An another instance of this script is already running"
   exit 1
fi

if [[ $1 == 'clean' ]]
	then
		echo "clean command passed"
		exit 1
	else
		if mountpoint -q /mnt/samba
			then
				rsync -vruO --delete-after /mnt/dlink_nfs/backup-test /mnt/samba/

		fi

	cd /mnt/dlink_nfs/backup-test/

	shopt -s dotglob
	shopt -s nullglob
	array=(*/)
	echo runing s3

	for dir in "${array[@]}"
	 do 
		echo "Currently Running S3 on $dir"
		dir=${dir%/}
	        timeout 30m s3cmd $s3_cmd $dir $s3_bucket
	 done
fi
