#!/bin/bash
#VARIABLE DECLARATIONS

test="TRUE"

FOLDER_NFS=/mnt/dlink_nfs
DIRNAME=$(hostname)
#This is used to ensure only one instance of the calling script is running
script_name=$(basename -- "$0")
s3_cmd="sync -rHv --no-check-md5 --delete-removed --skip-existing --acl-private --continue-put --storage-class=STANDARD_IA  --exclude-from=/mnt/dlink_nfs/backup-script/s3_exclude"
s3_bucket=s3://linux-bck/backup/
